# ref: https://github.com/actions/runner-images
name: amd64 Linux

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        python: [
          {version: "3.9"},
          {version: "3.10"},
          {version: "3.11"},
          {version: "3.12"},
        ]
      fail-fast: false
    name: Linux • Python-${{ matrix.python.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install deps
        run: python3 -m pip install -r requirements.txt
      - name: Run
        run: python3 main.py
